# nginx-kustomization.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-kustomize
  namespace: flux-system
spec:
  interval: 1m
  path: ./k8s/nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: nginx-k8s
  targetNamespace: nginx
  timeout: 2m 
