apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-config-infra
  namespace: flux-system
spec:
  interval: 1m
  path: ./infrastructure/nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-config
  targetNamespace: rathyatra-ns
