apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: rathyatra-ns
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: "15.14.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    service:
      type: LoadBalancer
      port: 80