apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-kustomization
  namespace: flux-system
spec:
  interval: 1m
  path: .
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-config
  targetNamespace: rathyatra-ns
