apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo-default
  namespace: flux-system
spec:
  interval: 5m0s
  path: ../../kustomize/overlays/default
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo
  targetNamespace: default
