apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo-prod
  namespace: flux-system
spec:
  interval: 5m0s
  path: ../../kustomize/overlays/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo
  targetNamespace: prod
