apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: flux-k8s-multi-env
  secretRef:
    name: flux-system
  url: https://github.com/nanisravankumar/flux-cd.git
