apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-kustomization
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/my-cluster/flux-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system      # This should match the bootstrapped Git repo
  targetNamespace: flux-system
