---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: cluster-config
spec:
  chart:
    spec:
      chart: nginx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: nginx
  targetNamespace: nginx
  values:
    service:
      type: LoadBalancer
    replicaCount: 2
